categories:
  - name: aardappelen,-groente-en-fruit
    url: "https://www.jumbo.com/producten/aardappelen,-groente-en-fruit/"
  - name: verse-maaltijden-en-gemak
    url: "https://www.jumbo.com/producten/verse-maaltijden-en-gemak/"