categories:
  - name: aardappelen,-groente-en-fruit
    url: "https://www.jumbo.com/producten/aardappelen,-groente-en-fruit/"
  - name: verse-maaltijden-en-gemak
    url: "https://www.jumbo.com/producten/verse-maaltijden-en-gemak/"
  - name: vlees,-vis-en-vega
    url: "https://www.jumbo.com/producten/vlees,-vis-en-vega/"
  - name: brood-en-gebak
    url: "https://www.jumbo.com/producten/brood-en-gebak/"
  - name: vleeswaren,-kaas-en-tapas
    url: "https://www.jumbo.com/producten/vleeswaren,-kaas-en-tapas/"
  - name: zuivel,-eieren,-boter
    url: "https://www.jumbo.com/producten/zuivel,-eieren,-boter/"
  - name: conserven,-soepen,-sauzen,-olien
    url: "https://www.jumbo.com/producten/conserven,-soepen,-sauzen,-olien/"
  - name: wereldkeukens,-kruiden,-pasta-en-rijst
    url: "https://www.jumbo.com/producten/wereldkeukens,-kruiden,-pasta-en-rijst/"
  - name: ontbijt,-broodbeleg-en-bakproducten
    url: "https://www.jumbo.com/producten/ontbijt,-broodbeleg-en-bakproducten/"
  - name: koek,-snoep,-chocolade-en-chips
    url: "https://www.jumbo.com/producten/koek,-snoep,-chocolade-en-chips/"